# Generated by Django 3.1.4 on 2020-12-16 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201216_0217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
